# Generated by Django 5.0.2 on 2024-04-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='tags',
            old_name='tagname',
            new_name='caption',
        ),
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='lastname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
