# Generated by Django 5.0.2 on 2024-04-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_name_author_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='picture',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
